# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       xorg-x11-drv-mouse

# >> macros
# << macros

Summary:    X.Org X11 mouse input driver
Version:    1.8.1
Release:    1
Group:      Graphics/X11
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/releases/individual/driver/xf86-input-mouse-%{version}.tar.bz2
Source100:  xorg-x11-drv-mouse.yaml
Requires:   xorg-x11-server-Xorg
BuildRequires:  pkgconfig(xorg-macros) >= 1.8
BuildRequires:  pkgconfig(xorg-server) >= 1.7
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(inputproto)

%description
%{summary}.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.


%prep
%setup -q -n xf86-input-mouse-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
# >> files
%(pkg-config xorg-server --variable=moduledir )/input/mouse_drv.so
%doc %{_mandir}/man4/mousedrv.4*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/xorg/xf86-mouse-properties.h
%{_libdir}/pkgconfig/xorg-mouse.pc
# << files devel
